name: neurosity
description: Neurosity SDK
version: 0.0.1
homepage: https://neurosity.majidhajian.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  firebase: ^9.0.2
  firebase_auth_dart: ^0.1.1-dev.5
  firebase_core_dart: ^0.1.1-dev.2
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  lints: ^1.0.0
  test: ^1.16.0
