name: neurosity
description: Neurosity SDK
version: 0.0.2
homepage: https://neurosity.majidhajian.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  firebase: ^9.0.3
  firebase_auth_dart: ^1.0.0
  firebase_core_dart: ^1.0.0
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.21.3

false_secrets:
  - /lib/src/api/firebase/firebase.dart
